
include:
  - project: 'freedesktop/ci-templates'
    ref: 59de540b620c45739871d1a073d76d5521989d11
    file: '/templates/debian.yml'

stages:
  - containers-build
  - test

.debian:
  variables:
    FDO_UPSTREAM_REPO: wayland/wayland-protocols
    FDO_DISTRIBUTION_VERSION: bullseye
    FDO_DISTRIBUTION_PACKAGES: 'build-essential automake autoconf libtool pkg-config libwayland-dev meson'
    FDO_DISTRIBUTION_TAG: '2021-03-24.0'

container_build:
  extends:
    - .debian
    - .fdo.container-build@debian
  stage: containers-build
  variables:
    GIT_STRATEGY: none

test:
  stage: test
  extends:
    - .debian
    - .fdo.distribution-image@debian
  script:
    - ./autogen.sh
    - make check
